## A region based sales data

In [44]:
# Imports
import pandas as pd

In [45]:
sales_data = pd.DataFrame({
    "region": ["Greater Accra", "Ashanti", "Western", "Eastern", "Volta", "Bono"],
    "product": ["Tilapia", "Cassava", "Maize", "Potatoes", "Rice", "Yam"],
    "sales": [216, 82, 110, 108, 154, 115]
})

In [46]:
sales_data.head()

          region   product  sales
0  Greater Accra   Tilapia    216
1        Ashanti   Cassava     82
2        Western     Maize    110
3        Eastern  Potatoes    108
4          Volta      Rice    154

In [47]:
sales_data.shape

(6, 3)

In [48]:
sales_data.dtypes

region       str
product      str
sales      int64
dtype: object

In [49]:
sales_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   region   6 non-null      str
 1   product  6 non-null      str
 2   sales    6 non-null      int64
dtypes: int64(1), str(2)
memory usage: 276.0 bytes

In [50]:
sales_data.describe()

            sales
count    6.000000
mean   130.833333
std     47.709188
min     82.000000
25%    108.500000
50%    112.500000
75%    144.250000
max    216.000000

In [51]:
sales_data.loc[:, "sales"]

0    216
1     82
2    110
3    108
4    154
5    115
Name: sales, dtype: int64

In [52]:
sales_data.iloc[0,1]

'Tilapia'

In [53]:
#Add a new row to the dataframe
sales_data.loc[len(sales_data)] = ["Northern", "Millet", None]

In [54]:
sales_data

          region   product sales
0  Greater Accra   Tilapia   216
1        Ashanti   Cassava    82
2        Western     Maize   110
3        Eastern  Potatoes   108
4          Volta      Rice   154
5           Bono       Yam   115
6       Northern    Millet   NaN

In [55]:
# Remove row with missing value
sales_data.dropna(inplace=True)

In [56]:
sales_data

          region   product sales
0  Greater Accra   Tilapia   216
1        Ashanti   Cassava    82
2        Western     Maize   110
3        Eastern  Potatoes   108
4          Volta      Rice   154
5           Bono       Yam   115

In [57]:
#Add the row with missing column again
sales_data.loc[len(sales_data)] = ["Northern", "Millet", None]

In [58]:
sales_data

          region   product sales
0  Greater Accra   Tilapia   216
1        Ashanti   Cassava    82
2        Western     Maize   110
3        Eastern  Potatoes   108
4          Volta      Rice   154
5           Bono       Yam   115
6       Northern    Millet   NaN

In [59]:
#Fill missing 
sales_data.fillna(0)

          region   product sales
0  Greater Accra   Tilapia   216
1        Ashanti   Cassava    82
2        Western     Maize   110
3        Eastern  Potatoes   108
4          Volta      Rice   154
5           Bono       Yam   115
6       Northern    Millet     0

In [60]:
sales_data.fillna(0)

          region   product sales
0  Greater Accra   Tilapia   216
1        Ashanti   Cassava    82
2        Western     Maize   110
3        Eastern  Potatoes   108
4          Volta      Rice   154
5           Bono       Yam   115
6       Northern    Millet     0

In [67]:
sales_data.groupby("region")["sales"].mean()

region
Ashanti           82.0
Bono             115.0
Eastern          108.0
Greater Accra    216.0
Northern           NaN
Volta            154.0
Western          110.0
Name: sales, dtype: object