In [1]:
#imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
raw_data = {
    "branch": ["Accra", "Kumasi", "Takoradi", "Accra", "Kumasi", "Takoradi", "Accra", "Kumasi"],
    "category": ["Electronics", "Clothing", "Electronics", "Food", "Food", "Clothing", "Electronics", "Clothing"],
    "employees": [45, 30, 28, 60, 35, None, 50, 25],
    "sales_2022": [12000, 8500, 7200, 15000, 9100, 6800, 13500, 7900],
    "sales_2023": [14500, 9200, 7800, 16200, 9800, 7100, 15000, 8400],
    "sales_2024": [16000, 10100, None, 18000, 10500, 7600, 16800, 9200],
    "active":["True", "True", "False", "True", "True", "True", "True", "False"]
}

In [3]:
# Create a dataframe

df = pd.DataFrame(raw_data)
df

     branch     category  employees  sales_2022  sales_2023  sales_2024 active
0     Accra  Electronics       45.0       12000       14500     16000.0   True
1    Kumasi     Clothing       30.0        8500        9200     10100.0   True
2  Takoradi  Electronics       28.0        7200        7800         NaN  False
3     Accra         Food       60.0       15000       16200     18000.0   True
4    Kumasi         Food       35.0        9100        9800     10500.0   True
5  Takoradi     Clothing        NaN        6800        7100      7600.0   True
6     Accra  Electronics       50.0       13500       15000     16800.0   True
7    Kumasi     Clothing       25.0        7900        8400      9200.0  False

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   branch      8 non-null      str
 1   category    8 non-null      str
 2   employees   7 non-null      float64
 3   sales_2022  8 non-null      int64
 4   sales_2023  8 non-null      int64
 5   sales_2024  7 non-null      float64
 6   active      8 non-null      str
dtypes: float64(2), int64(2), str(3)
memory usage: 580.0 bytes

In [5]:
df.describe()

       employees    sales_2022    sales_2023    sales_2024
count   7.000000      8.000000      8.000000      7.000000
mean   39.000000  10000.000000  11000.000000  12600.000000
std    12.987173   3089.151525   3628.852633   4194.838098
min    25.000000   6800.000000   7100.000000   7600.000000
25%    29.000000   7725.000000   8250.000000   9650.000000
50%    35.000000   8800.000000   9500.000000  10500.000000
75%    47.500000  12375.000000  14625.000000  16400.000000
max    60.000000  15000.000000  16200.000000  18000.000000

In [6]:
df["employees"] = df["employees"].fillna(df["employees"].median())
df

     branch     category  employees  sales_2022  sales_2023  sales_2024 active
0     Accra  Electronics       45.0       12000       14500     16000.0   True
1    Kumasi     Clothing       30.0        8500        9200     10100.0   True
2  Takoradi  Electronics       28.0        7200        7800         NaN  False
3     Accra         Food       60.0       15000       16200     18000.0   True
4    Kumasi         Food       35.0        9100        9800     10500.0   True
5  Takoradi     Clothing       35.0        6800        7100      7600.0   True
6     Accra  Electronics       50.0       13500       15000     16800.0   True
7    Kumasi     Clothing       25.0        7900        8400      9200.0  False

In [7]:
df["sales_2024"] = df["sales_2024"].fillna(df["sales_2024"].mean())
df

     branch     category  employees  sales_2022  sales_2023  sales_2024 active
0     Accra  Electronics       45.0       12000       14500     16000.0   True
1    Kumasi     Clothing       30.0        8500        9200     10100.0   True
2  Takoradi  Electronics       28.0        7200        7800     12600.0  False
3     Accra         Food       60.0       15000       16200     18000.0   True
4    Kumasi         Food       35.0        9100        9800     10500.0   True
5  Takoradi     Clothing       35.0        6800        7100      7600.0   True
6     Accra  Electronics       50.0       13500       15000     16800.0   True
7    Kumasi     Clothing       25.0        7900        8400      9200.0  False

In [10]:
df[["sales_2022", "sales_2023"]] = df[["sales_2022", "sales_2023"]].astype(float)

In [11]:
df["active"] = df["active"].astype(bool)

In [12]:
df["employees"] = df["employees"].astype(int)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   branch      8 non-null      str
 1   category    8 non-null      str
 2   employees   8 non-null      int64
 3   sales_2022  8 non-null      float64
 4   sales_2023  8 non-null      float64
 5   sales_2024  8 non-null      float64
 6   active      8 non-null      bool
dtypes: bool(1), float64(3), int64(1), str(2)
memory usage: 524.0 bytes

In [14]:
df

,branch,category,employees,sales_2022,sales_2023,sales_2024,active
0,Accra,Electronics,45,12000.0,14500.0,16000.0,True
1,Kumasi,Clothing,30,8500.0,9200.0,10100.0,True
2,Takoradi,Electronics,28,7200.0,7800.0,12600.0,True
3,Accra,Food,60,15000.0,16200.0,18000.0,True
4,Kumasi,Food,35,9100.0,9800.0,10500.0,True
5,Takoradi,Clothing,35,6800.0,7100.0,7600.0,True
6,Accra,Electronics,50,13500.0,15000.0,16800.0,True
7,Kumasi,Clothing,25,7900.0,8400.0,9200.0,True

In [15]:
df["active"] = df["active"].astype(str)